build:
  - .github/**/*

scripts:
  - buildSrc/src/main/kotlin/**/script/**/*.kts

dependencies:
  - buildSrc/**/*
  - gradlePlugin/**/*

documentation:
  - docs/**/*
  - README.md
  - LICENSE
  - CHANGELOG.md
  - CODE-OF-CONDUCT.md
  - CONTRIBUTION.md
  - SECURITY.md

# Library
test-utils:
  - test-utils/**/*

test-utils-coroutine:
  - test-utils-coroutine/**/*

test-utils-ktor:
  - test-utils-ktor/**/*

test-utils-fixture:
  - test-utils-fixture/**/*
