build:
  - .github/**/*

scripts:
  - buildSrc/src/main/kotlin/**/script/**/*.kts

dependencies:
  - buildSrc/**/*
  - gradlePlugin/test-utils-dependency/**/*

documentation:
  - docs/**/*
  - README.adoc
  - LICENSE
  - CHANGELOG.adoc
  - CODE-OF-CONDUCT.adoc
  - CONTRIBUTION.adoc
  - readmeOSS.adoc

# Library
test-utils:
  - test-utils/**/*

test-utils-coroutine:
  - test-utils-coroutine/**/*
