name: Run Checks

on:
  workflow_call:

concurrency:
  group: validation-${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: false

jobs:
  check:
    strategy:
      matrix:
        config: [
          { target: android, os: ubuntu-latest, tasks: testDebugUnitTest testReleaseUnitTest, continueOnError: false },
          { target: apple, os: macos-latest, tasks: iosX64Test iosSimulatorArm64Test, continueOnError: false }, # macosX64Test macosArm64Test tvosX64Test tvosSimulatorArm64Test watchosX64Test watchosSimulatorArm64Test, continueOnError: false },
          # { target: windows, os: windows-latest, tasks: windowsTest, continueOnError: true }, # https://github.com/square/okio/issues/951
          { target: linux, os: ubuntu-latest, tasks: linuxX64Test, continueOnError: false },
          { target: js, os: ubuntu-latest, tasks: jsTest, continueOnError: false },
          { target: jvm, os: ubuntu-latest, tasks: jvmTest, continueOnError: false },
        ]
    runs-on: ${{ matrix.config.os }}

    name: Check ${{ matrix.config.target }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          cache: gradle

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Cleanup
        run: ./gradlew clean

      - name: Test ${{ matrix.config.target }} targets
        continue-on-error: ${{ matrix.config.continueOnError }}
        run: ./gradlew ${{ matrix.config.tasks }}
