name: Antibytes CI - Publish Rolling Release

on:
  workflow_dispatch:
    tags:
      - 'v*'

jobs:
  check:
    uses: ./.github/workflows/ci-check.yml

  publish-rolling-release:
    runs-on: macos-latest
    needs: check

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          cache: gradle

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build
      - name: Publish to Rolling Release Repository
        run: ./gradlew publishRollingRelease --no-parallel
