name: Antibytes CI - Publish Rolling Release

on:
  workflow_dispatch:
    tags:
      - 'v*'

jobs:
  check:
    uses: bitpogo/workflows/.github/workflows/shared-kmp-check.yml@main #./.github/workflows/ci-check.yml
    with:
      platforms: "['android', 'ios', 'linux', 'js', 'jvm']"

  publish-rolling-release:
    runs-on: macos-latest
      needs: check
      uses: bitpogo/workflows/.github/workflows/shared-rolling-release-validation@main
      secrets:
        upload-username: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
        upload-token: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
